# ----------
#  Auto Totem
# ----------
# If player moves totem from inventory faster than this number he will be flagged as cheater
maximumAllowedTicksToChangeTotemAfterPop: 10
# If server's TPS are lower than this player won't get punished but will show logs to console and admins
minimumTpsForFlagsCount: 17.5

# Prevent people using "binds" for auto equipping totems
detectUnknownTypeActionsWhenSwitchingToOffhand: true

punishAfterFlags: 3
# Commands that will be executed after reaching desired number of flags. Use %player% for player's name
punishments:
#  - "kill %player%"
  - "kick %player%"

# Translation

# Message shown to administrators when player is flagged as cheater, you can use  Minimessage format https://docs.advntr.dev/minimessage/format.html
adminMessage: "<rainbow>Player %player% replaced his totem in under %ticks% ticks ඞඞඞ</rainbow>"
# Message logged to console, you can's use minimessage there
consoleMessage: "Player %player% replaced his totem in under %ticks% with ping %ping%ms (%flagged%/%popped%)"