# If player moves totem from inventory faster than this number he will be flagged as cheater
maximumAllowedTicksToChangeTotem: 10
# If server's TPS are lower than this player won't get punished but will show logs to console and admins
minimumTpsForFlagsCount: 17.5
punishAfterFlags: 3
# Commands that will be executed after reaching desired number of flags. Use %player% for player's name
punishments:
#  - "kill %player%"
  - "kick %player%"

# Message shown to administrators when player is flagged as cheater
adminMessage: "<rainbow>Gracz %player% uzył totemu w mniej niż %ticks% ticków. !SUS!</rainbow>"