maximumAllowedTicksToChangeTotem: 10
minimumTpsForFlagsCount: 17.5
punishAfterFlags: 3
punishments:
#  - "kill {player}"
  - "kick {player}"


adminMessage: "<rainbow>Gracz %player% uzył totemu w mniej niż %ticks% ticków. !SUS!</rainbow>"